find_package(PkgConfig)
pkg_check_modules(PC_QT5WEBRTC Qt5WebRTC)

find_path(QT5WEBRTC_INCLUDE_DIRS
    NAMES wrtcint.h
    HINTS ${PC_QT5WEBRTC_INCLUDE_DIRS} ${PC_QT5WEBRTC_INCLUDE_DIRS}
)

set(QT5WEBRTC_LIBRARIES "")
set(QT5WEBRTC_NAMES ${PC_QT5WEBRTC_LIBRARIES})
foreach (_library ${QT5WEBRTC_NAMES})
  find_library(QT5WEBRTC_LIBRARIES_${_library} ${_library}
    HINTS ${PC_QT5WEBRTC_LIBDIR} ${PC_QT5WEBRTC_LIBRARY_DIRS}
  )
  set(QT5WEBRTC_LIBRARIES ${QT5WEBRTC_LIBRARIES} ${QT5WEBRTC_LIBRARIES_${_library}})
endforeach ()

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(QT5WEBRTC DEFAULT_MSG QT5WEBRTC_INCLUDE_DIRS QT5WEBRTC_LIBRARIES)

message(STATUS "found qt5webrtc: ${QT5WEBRTC_LIBRARIES}")
