
[
    NoInterfaceObject,
    Conditional=SPEECH_RECOGNITION,
    Constructor
] interface SpeechGrammarList {
    readonly attribute unsigned long length;
    getter SpeechGrammar item(unsigned long index);
    [CallWith=ScriptExecutionContext]void addFromUri(DOMString src, optional double weight);
    void addFromString(DOMString string, optional float weight);
};
