
[
    NoInterfaceObject,
    Conditional=SPEECH_RECOGNITION,
] interface SpeechRecognitionError : Event {
    [InitializedByEventConstructor] readonly attribute DOMString error;
    [InitializedByEventConstructor] readonly attribute DOMString message;
};
