[
    NoInterfaceObject,
    Conditional=TV_CONTROL,
    ActiveDOMObject,
] interface TVManager : EventTarget {
    Promise                      getTuners();
    attribute EventHandler       ontunerchanged;
};
