[
    NoInterfaceObject,
    Conditional=TV_CONTROL,
    ActiveDOMObject,
] interface TVManager : EventTarget {
    sequence<TVTuner>            getTuners ();
//    attribute EventHandler       ontunerchanged;
};
