

[
    Conditional=TV_RECORDING_CHANGED
]


interface TVRecordingChangedEvent : Event {
    readonly attribute DOMString  id;
    readonly attribute boolean    isTimeChange;
    readonly attribute boolean    isStateChange;
    readonly attribute DOMString? errorName;
};
