enum TVSourceType { "dvb-t", "dvb-t2", "dvb-c", "dvb-c2", "dvb-s", "dvb-s2", "dvb-h", "dvb-sh", "atsc", "atsc-m-h", "isdb-t", "isdb-tb", "isdb-s", "isdb-c", "1seg", "dtmb", "cmmb", "t-dmb", "s-dmb" };

/*dictionary TVStartScanningOptions {
    boolean isRescanned = false;
};*/

[
    Conditional=TV_CONTROL,
] interface TVSource : EventTarget {
    sequence<TVChannel> getChannels ();
    void                setCurrentChannel (DOMString channelNumber);
    void                startScanning ();//optional TVStartScanningOptions options);
    void                stopScanning ();
    readonly        attribute TVTuner      tuner;
    readonly        attribute TVSourceType type;
    readonly        attribute boolean      isScanning;
    readonly        attribute TVChannel?   currentChannel;
    //                attribute EventHandler oncurrentchannelchanged;
    //                attribute EventHandler oneitbroadcasted;
    //                attribute EventHandler onemergencyalerted;
    //                attribute EventHandler onscanningstatechanged;
};
