enum TVTunerChangedEventOperation { "added", "removed" };

[
    Conditional=TV_CONTROL
] interface TVTunerChangedEvent : Event {
    readonly        attribute TVTunerChangedEventOperation operation;
    readonly        attribute DOMString                    id;
};
